all:
  root: '/scr1/users/leej39/genomeCompTest'
  taxa_assembly: '/scr1/users/leej39/genomeCompTest/taxa_assembly.txt'
  admin_email: 'junglee0713@gmail.com' 

download_genome:
  script: '/home/leej39/genomeComp/scripts/download_genome.bash'
